final Map<String, String> sectionTranslations = {
  'அறத்துப்பால்': 'Virtue',
  'பொருட்பால்': 'Wealth',
  'காமத்துப்பால்': 'Love',
};

final Map<String, String> chapterEnglishMap = {
  "கடவுள் வாழ்த்து": "Praise of God",
  "வான் சிறப்பு": "Praise of Rain",
  "நீத்தார் பெருமை": "Greatness of Renunciation",
  "அரண் வலியுறுத்தல்": "Righteousness",
  "இல்வாழ்க்கை": "Family Life",
  "பெண்மை": "Wives Welfare",
  "மக்கட்பேறு": "Children",
  "அன்பு": "Kindness",
  "விருந்தோம்பல்": "Hospitality",
  "இனியவகையியல்": "Sweet Talk",
  "தீமை தீய பயனுள்": "Gratitude",
  "ஒழுக்கம்": "Balanced",
  "அடக்கம்": "Self-Control",
  "ஒழிவியல்": "Right Conduct",
  "கள்ளாமை": "Adultery",
  "மடிதல்": "Patience",
  "பொறைமை": "Envy",
  "அலவலம்": "Non-Coveting",
  "பிறனயம்": "Not Back-Biting",
  "நயவஞ்சனம்": "Frivolity of Speech",
  "பழியஞ்சல்": "Fear of Evil Deeds",
  "அஞ்சாமை": "Decorum",
  "அருளுடைமை": "Liberality",
  "புகழ்": "Renown",
  "இரக்கம்": "Compassion",
  "அன்புடைமை": "Abstaining from Meat",
  "தவம்": "Penance",
  "குடில்செயல்": "Improper Conduct",
  "களவு": "Non-Stealing",
  "வாய்மை": "Truth",
  "அகிருதல்": "Not Getting Angry",
  "அவஞ்செய்யாமை": "Not Doing Evil",
  "அருசி அறுக்காமை": "Not Killing",
  "வாழ்க்கை நிலைமை": "Instability",
  "வெறுப்புறுத்தல்": "Renunciation",
  "அறிவுறுத்தல்": "Realising Knowledge",
  "விருப்புறுத்தல்": "Destruction of Desire",
  "அதிகாரம்": "Fate",
  "பெருமை": "Majesty",
  "கல்வி": "Learning",
  "கற்பில்லைமை": "Non-Learning",
  "செவிவாய்ப்பு": "Hearing",
  "அறிவு": "Knowledge",
  "குற்றங்களை ஒழித்தல்": "Restraining Faults",
  "மூப்புடன் சேர்ந்திருத்தல்": "Association with Elders",
  "தாழ்ந்தவர் ஒழுக்கம்": "Avoiding Low Company",
  "செயற்கைத் திட்டம்": "Action after Due Deliberation",
  "பகைவர் வலிமை அறிவல்": "Knowing the Enemy's Strength",
  "காலம் அறிதல்": "Knowing the Time",
  "இடம் அறிதல்": "Knowing the Place",
  "வினை துவக்குதல்": "Engaging Servants After Test",
  "பதவி சேர்த்தல்": "Appointment According to Merit",
  "அன்பினால் உறவோம்பல்": "Cherishing One's Kindred",
  "மறப்பாமை": "Against Forgetfulness",
  "அரசு அறம்": "Righteous Sceptre",
  "அரசு அறமின்றி": "Unrighteous Rule",
  "பெருமைக்குரிய அரசு": "Tyranny",
  "இனிமை பேசுதல்": "Kindliness",
  "அறிவுடையர் தேடல்": "Spies",
  "உழைப்பு": "Exertion",
  "ஆர்வமில்லாமை": "Against Sloth",
  "துணிவு": "Perseverance",
  "அச்சம்": "Courage",
  "அமைச்சர்": "Ministers",
  "நல்ல சொல்": "Good Speech",
  "அறம் செய்யும் தன்மை": "Purity in Action",
  "தீர்மானம்": "Resoluteness",
  "செயற்கை வகை": "Means of Action",
  "தூதுவினை": "Embassy",
  "அரசுடன் ஒத்துழைப்பு": "Co-operation with King",
  "நோக்கம் உணர்தல்": "Reading One's Intentions",
  "மன்றம் அறிதல்": "Knowing the Assembly",
  "மன்றத்தில் அஞ்சாமை": "Not to be Afraid of Assembly",
  "நாடு": "Country",
  "கோட்டை": "Fortress",
  "செல்வம் பெருக்கல்": "Acquisition of Wealth",
  "படை மதிப்பு": "Value of an Army",
  "படைத் துணிவு": "Courage of the Army",
  "நட்பு": "Friendship",
  "நட்பு அறிதல்": "Identifying Friends",
  "நட்பு நிலை": "Friendship Behaviour",
  "தீய நட்பு": "Bad Friendship",
  "பொய் நட்பு": "False Alliance",
  "முட்டாள்தனம்": "Stupidity",
  "அறியாமை": "Ignorance",
  "முரண்பாடு": "Discord",
  "பகைமை": "Enmity",
  "உள்நட்பு உணர்தல்": "Internal Foes",
  "பெரியாரை பழிக்காமை": "Not Censuring the Great",
  "மனைவி அச்சம்": "Fear of Wife",
  "வெறும் பெண்கள்": "Prostitutes",
  "மது தவிர்க்கல்": "Avoiding Alcohol",
  "சூதாட்டம்": "Gambling",
  "மருந்து": "Medicine",
  "பிறவி மரபு": "Noble Lineage",
  "மரியாதை": "Honour",
  "மிகுதி": "Greatness",
  "நல்ல ஒழுக்கம்": "Good Conduct",
  "மரியாதை காட்டல்": "Courtesy",
  "பயனற்ற செல்வம்": "Unprofitable Wealth",
  "முன்னிலை தன்மை": "Modesty",
  "குடும்பம் உயர்த்தல்": "Exalting One's Family",
  "விவசாயம்": "Agriculture",
  "வறுமை": "Poverty",
  "விருந்து தேடல்": "Begging",
  "விருந்து அஞ்சல்": "Fear of Begging",
  "சிறுமை": "Meanness",
  "காதலின் குழப்பம்": "Lover's Distraction",
  "அன்பின் அறிகுறி": "Reading Love's Signs",
  "காதல் பேரின்பம்": "Ecstasy of Love's Union",
  "அவளின் பெருமை": "His Lady",
  "அன்பின் உறுதி": "Affirmation of Love",
  "தடுமாற்றமின்றி கூறல்": "Speaking Out Unabashed",
  "அறிவுறும் கிசுகிசு": "Rumours of Secret Love",
  "பிரிவின் துன்பம்": "The Pangs of Separation",
  "பிரிந்தவரின் அழுகை": "The Cry of the Separated",
  "கண்ணின் வருத்தம்": "On Eyes That Languish",
  "காதல் நிறம்": "Grieving Over Love's Pallor",
  "தனிமை உணர்வு": "Feeling All Alone",
  "இன்ப நினைவு": "Recollecting the Pleasures of Love",
  "காதல் கனவு": "Dreams of Love",
  "மாலை சோகம்": "Sunset and Sorrow",
  "உடல் குன்றல்": "Wasting Away",
  "அவளின் தனித்தன்மை": "Soliloquy of the Lady Love",
  "முன்னிலை இழப்பு": "Loss of Modesty",
  "இருவரின் தவிப்பு": "Distress of each Towards the Other",
  "அறிகுறிகள் கூறல்": "Speaking on the Signs",
  "இணைவை விரும்பல்": "Yearning After Union",
  "மனத்துடன் பேசல்": "Speaking with the Mind",
  "விடுபடல்": "Lovers' Misunderstanding",
  "மயக்க அறிதல்": "Subtlety of Lovers' Misunderstanding",
  "விடுபட்ட இன்பம்": "Pleasures of Lovers' Misunderstanding"
};
